name: Tests

on:
  pull_request:
    branches:
      - 'master'
    paths-ignore:
      - '*.md'

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run Unit tests
        run: bash ./gradlew testDebugUnitTest --stacktrace

  apks:
    name: APKs
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Assemble Development APK
        run: bash ./gradlew assembleDebug --stacktrace

      - name: Upload Development APK
        uses: actions/upload-artifact@v1
        with:
          name: apk-development
          path: android-ui/build/outputs/apk/debug/android-ui-debug.apk

      - name: Assemble Instrumentation Tests APK
        run: bash ./gradlew assembleDebugAndroidTest

      - name: Upload Instrumentation Tests APK
        uses: actions/upload-artifact@v1
        with:
          name: apk-tests
          path: android-ui/build/outputs/apk/androidTest/debug/android-ui-debug-androidTest.apk

  test_lab:
    name: Instrumentation Tests
    needs: apks
    runs-on: ubuntu-18.04
    env:
      GOOGLE_CLOUD_PROJECT_PATH: test-lab-dxpqby473161q-hj2c770js967m
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Download APKs
        uses: actions/download-artifact@v1
        with:
          name: apk-development

      - name: Download UI Tests APK
        uses: actions/download-artifact@v1
        with:
          name: apk-tests

      - name: Authenticate into GCloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '270.0.0'
          service_account_key: ${{ secrets.FIREBASE_ADMIN_SERVICE_KEY }}

      - name: Configure GCloud project ID
        run: gcloud config set project $FIREBASE_PROJECT_ID
        env:
          FIREBASE_PROJECT_ID: boletinhos-5b614

      - name: Run Instrumentation Tests
        run: >
          gcloud firebase test android run --type instrumentation
          --app apk-development/android-ui-debug.apk
          --test apk-tests/android-ui-debug-androidTest.apk
          --device model=Pixel2,version=28,locale=en_US,orientation=portrait
          --no-use-orchestrator
          --environment-variables coverage=true,coverageFile="/sdcard/coverage.ec"
          --directories-to-pull=/sdcard
          --no-record-video

      - name: Create Instrumentation Coverage folder
        run: mkdir -p instrumentation/coverage/

      - name: Download coverage file from Firebase Test Lab
        run: >
          gsutil cp -U gs://$GOOGLE_CLOUD_PROJECT_PATH/**/sdcard/*.ec $GITHUB_WORKSPACE/instrumentation/coverage/

      - name: Upload Instrumentation Coverage
        uses: actions/upload-artifact@v1
        with:
          name: coverage
          path: instrumentation/coverage/

      - name: Move Instrumentation Coverage to app outputs dir
        run: >
          mkdir -p android-ui/build/outputs/code-coverage/connected && cp instrumentation/coverage/*.ec android-ui/build/outputs/code-coverage/connected/coverage.ec

  code_coverage:
    name: Code Coverage
    needs: test_lab
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Generate Jacoco Reports
        run: bash ./gradlew clean projectCodeCoverageReport

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true